### ISSUE TITLE
After using log.into, the log in the context becomes undefined.

### ISSUE THREAD

**Issue by MAST1999** [bogeychan/elysia-logger#21]
### What versions are running?

Bun version: 1.1.25

Deps:
```json
{
	"dependencies": {
		"@bogeychan/elysia-logger": "^0.1.1",
		"@elysiajs/cors": "^1.1.0",
		"@elysiajs/opentelemetry": "^1.1.4",
		"@elysiajs/server-timing": "^1.1.0",
		"@elysiajs/swagger": "^1.1.1",
		"@giatec/domain": "workspace:*",
		"@giatec/shared": "workspace:*",
		"@opentelemetry/api": "^1.0.0",
		"@opentelemetry/exporter-logs-otlp-grpc": "^0.52.1",
		"@opentelemetry/exporter-trace-otlp-grpc": "^0.52.0",
		"@opentelemetry/resources": "^1.25.1",
		"@opentelemetry/sdk-logs": "^0.52.1",
		"@opentelemetry/sdk-trace-node": "^1.25.1",
		"@sinclair/typebox": "^0.32.35",
		"date-fns": "^3.6.0",
		"elysia": "^1.1.6",
		"ky": "^1.7.1"
	}
}
```
TSConfig:
```json
{
	"$schema": "http://json.schemastore.org/tsconfig",
	"compilerOptions": {
		"lib": [
			"ESNext"
		],
		"module": "Preserve",
		"target": "ESNext",
		"verbatimModuleSyntax": true,
		"strict": true,
		"skipDefaultLibCheck": true,
		"downlevelIteration": true,
		"allowSyntheticDefaultImports": true,
		"forceConsistentCasingInFileNames": true,
		"moduleResolution": "Bundler",
		"rootDir": "."
}
```

### What steps can reproduce the bug?

Create a custom logger plugin like this:
```ts
import { createPinoLogger } from '@bogeychan/elysia-logger';
import Elysia from 'elysia';

export const log = createPinoLogger();

export const loggerPlugin = new Elysia({ name: 'logger' }).use(
	log.into({ autoLogging: process.env.NODE_ENV === 'development' }),
);
```

And then use loggerPlugin:
```ts
const app = new Elysia().use(loggerPlugin);
```

Now if you try to access the log function in the context, you'll see that it doesn't exits!
![image](https://github.com/user-attachments/assets/1fb36e30-67fa-4180-b066-e08abfd1096f)

But if you remove the condition from autoLogging and pass in true or false:
```ts
import { createPinoLogger } from '@bogeychan/elysia-logger';
import Elysia from 'elysia';

export const log = createPinoLogger();

export const loggerPlugin = new Elysia({ name: 'logger' }).use(
	log.into({ autoLogging: true }),
);
```

You'll see the log is now on the context but it might be undefined:
![image](https://github.com/user-attachments/assets/1b3419cc-e8ea-4e8c-9809-4ce00518cf28)

This also happens when using the logger exported from library directly as well.

### What is the expected behavior?

Using the logger should add the log property to the context and it shouldn't be undefined.

### What do you see instead?

After adding the log function it either isn't added or it can be undefined.

**Comment by bogeychan** [comment]
Thanks for reporting this finding!

You can do this as a workaround:

```ts
export const loggerPlugin = new Elysia({ name: "logger" }).use(
  log.into({ autoLogging: (process.env.NODE_ENV === "development") as false })
);
```

**Comment by bogeychan** [comment]
This should be fixed with `0.1.2`

**Comment by MAST1999** [comment]
I think I still have the problem with the new version:
![image](https://github.com/user-attachments/assets/83d2674a-666a-4c8d-b072-90010df3eb9d)

But only happens in the `error` function on a `gaurd`.
Something like this:

```ts
		app.use(authV1).guard(
			{
				headers: t.Object({
					'x-account-id': XAccountId,
				}),
				error: async ({ log, error: err, set }) => {
					log.error(err, "General Error");
				}
			})
```

For now I've just added an if check there.

**Comment by bogeychan** [comment]
This is intentional, as the `log` from `Context` may be `undefined` depending on the error-cause of the error. You must do this:

```ts
log?.error(err, "General Error");
// ^
```

I suggest you use the standalone logger instance there to make sure it's not `undefined`:

```ts
export const log = createPinoLogger();
//           ^

export const loggerPlugin = new Elysia({ name: "logger" }).use(
  log.into({ autoLogging: true })
);

new Elysia().use(loggerPlugin).guard({
  error: async ({ error: err, set }) => {
    log.error(err, "General Error");
//   ^
  },
});
```

**Comment by bogeychan** [comment]
You can find a full example here: https://github.com/bogeychan/elysia-logger/blob/f43118605010ef8e07d810df2f68f12190c2ee19/examples/on-error.ts

**Comment by MAST1999** [comment]
Oh, thanks for the explanation 👍

My issue is resolved.
